### ISSUE TITLE
TypeError: error.toJSON is not a function at BaseHttpHandler.processError

### ISSUE THREAD

**Issue by po3rin** [GoogleCloudPlatform/iap-gcip-web-toolkit#156]
I'm trying to verify an email when a user signs up via IAP, but I'm getting an error in the Google Cloud Identity Platform Blocking Functions.

Detailed error message cannot be confirmed because error cannot be parsed into JSON.

## sorce

package.json

```json
{
  "type": "module",
  "name": "sendCustomVerificationEmail",
  "version": "0.0.1",
  "dependencies": {
    "gcip-cloud-functions": "^0.1.0"
  }
}
```
index.js

```js
import gcipCloudFunctions from 'gcip-cloud-functions';

const authClient = new gcipCloudFunctions.Auth();

export const beforeCreate = authClient.functions().beforeCreateHandler((user, context) => {
  const locale = context.locale;
  if (user.email && !user.emailVerified) {
    // Send custom email verification on sign-up.
    return admin.auth().generateEmailVerificationLink(user.email).then((link) => {
      return sendCustomVerificationEmail(user.email, link, locale);
    }).catch((error) => {
      console.error(error)
    });
  }
  console.log('done');
});

```

log

```
sendCustomVerificationEmail-testfljwzva8h9we TypeError: error.toJSON is not a function at BaseHttpHandler.processError (/workspace/node_modules/gcip-cloud-functions/lib/cjs/auth/https.js:201:40)
sendCustomVerificationEmail-testfljwzva8h9we at /workspace/node_modules/gcip-cloud-functions/lib/cjs/auth/https.js:160:23
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Function execution took 899 ms, finished with status: 'crash'
```

How can I avoid this error?

**Comment by vicenters1** [comment]
I am having the EXACT same problem.

**Comment by TheMarex** [comment]
The error is triggered because the HTTP handler that is automatically created can't handle "regular" non-HTTP errors. So somewhere something is throwing an exception.

The way I debugged this is to copy the `gcip-cloud-functions` module from `node_modules` to a new `vendor/` directory and then depend on the GCIP module like so:

```
   "dependencies": {
    "gcip-cloud-functions": "file:./vendor/gcip-cloud-functions"
  }
```

You can modify `lib/cjs/auth/https.js` in the `processError` function to either not expect `toError` to exist or just `console.error()` the exception before it. The real exception should be printed in your cloud function logs now.

I would not ship it like ^ to production but in case anyone is stumped on how to debug this.
